server:
  port: 8013
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/tea_bus?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver